const cleanersData = [
  {
    businessName: "Ugo Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Enugu",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 1,
  },
  {
    businessName: "Tony Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Lagos",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 2,
  },
  {
    businessName: "Euvoria",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Enugu",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 3,
  },
  {
    businessName: "Nkem Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Abuja",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 4,
  },
  {
    businessName: "Sheri Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Uyo",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 5,
  },
  {
    businessName: "Anto Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Aba",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 6,
  },
  {
    businessName: "Diamond Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Warri",
    phoneNumber: "08040876440",
    name: "Tony Nnanna Njoku",
    id: 7,
  },
  {
    businessName: "Efe Daro Best",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Benin",
    phoneNumber: "08040876440",
    name: "Efe Daro",
    id: 8,
  },
  {
    businessName: "Iwegbu and Sons",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu Enugu",
    location: "Enugu",
    phoneNumber: "08040876440",
    name: "Uche Iwegbu",
    id: 9,
  },
  {
    businessName: "Omo and Co",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 3.5,
    address: "Shop 12 Sazodo Plaza, off deChills Auchi, Edo State",
    location: "Auchi",
    phoneNumber: "08040876440",
    name: "Omozele Osarieme",
    id: 10,
  },
  {
    businessName: "Oforegbu and Sons",
    favorite: false,
    desc: "We prioritize our customers satisfaction more than anything else, try us out today, and you'd have an experience of a lifetime.",
    img: "https://img-url.jpg",
    rating: 4.5,
    address: "Shop 12 Sazodo Plaza, off Nowas Junction Trans-Ekulu",
    location: "Enugu",
    phoneNumber: "08040876440",
    name: "Uchenna Ofor",
    id: 11,
  },
];

export default cleanersData;
