// import { AiFillStar } from "react-icons/ai";
// import uuid4 from "uuid4";

const data = [
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦48,000",
    newPrice: "₦32,500",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦49,000",
    newPrice: "₦37,800",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦34,400",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "flats",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "flats",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "flats",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "31,000",
    company: "Puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "31,000",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "flats",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "31,000",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sandals",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "31,000",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sandals",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sandals",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Vans",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "31,000",
    company: "puma",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "sneakers",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },

  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "₦32,900",
    company: "Nike",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "35,550",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "heels",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
  {
    // id: uuid4(),
    id: Math.random(),
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₦43,500",
    newPrice: "25,500",
    company: "Adidas",
    color: ["white", "red", "green", "black", "rose-pink", "blue"],
    size: ["44", "45", "46", "47"],
    category: "flats",

    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti iure placeat esse recusandae praesentium asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, laudantium.",
  },
];

// function getProductData(id) {
//   let productData = data.find((product) => product.id === id);
//   if (productData == undefined) {
//     console.log(";product not found");
//     return undefined;
//   }

//   return productData;
// }

// export { data, getProductData };
export default data;
// export { data };
